### ISSUE TITLE
Main Artsy link sends user to 404 page

### ISSUE THREAD

**Issue by cogell** [craigspaeth/craigspaeth#1]
Here is the problematic link: https://github.com/craigspaeth/craigspaeth/blob/master/views/index.jade#L7

**Comment by craigspaeth** [comment]
Thanks Cedric! Haha, yeah we used to have user profiles on our site... looks like i haven't updated my website in a while 😳

**Comment by cogell** [comment]
of course! just came across it as I was doing a quick scan before our meeting.
